version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: nx build demo-app2 
            - run: nx lint demo-app2
            - run: nx test demo-app2
workflows:
    build-and-test:
      jobs:
        - build-and-test